name: Lint

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check spelling
        uses: crate-ci/typos@master
